test_format = 1.0

#without Mosquitto
[default]
    test_upgrade_from.27311ad.name = "2022.2"
    test_upgrade_from.27311ad.args.mqtt_domain="sub.domain.tld"

#    exclude = ["package_linter", "install.root", "install.subdir", "install.private", "install.multi", "backup_restore", "upgrade", "upgrade.27311ad", "change_url"]
#    exclude = ["package_linter", "install.root", "install.private", "install.multi", "backup_restore", "upgrade", "upgrade.27311ad", "change_url"]

[With_Mosquitto_upgrade_with_mosquitto]
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    preupgrade = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """
    
    exclude = ["package_linter", "install.root", "install.subdir", "install.private", "install.multi", "backup_restore", "upgrade", "change_url"]

    test_upgrade_from.27311ad.name = "2022.2 with mosquitto"
    test_upgrade_from.27311ad.args.mqtt_domain="mqtt.domain.tld"