test_format = 1.0

#without Mosquitto
[default]
#Adding domain even if not used : snapshot are reused and may require domain to work
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    preupgrade = """
    set -euxo pipefail
    yunohost app setting domoticz mqtt_domain -v sub.domain.tld
    """

    args.mqtt_domain="sub.domain.tld"

    test_upgrade_from.c161dff.name = "2024.6"
    test_upgrade_from.c161dff.args.mqtt_domain="sub.domain.tld"
    test_upgrade_from.c161dff.args.domain="sub.domain.tld"
    test_upgrade_from.c161dff.args.path="/domoticz"

[With_Mosquitto_upgrade_with_mosquitto]
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    args.mqtt_domain="mqtt.domain.tld"

    exclude = ["package_linter"]

    test_upgrade_from.c161dff.name = "2024.6 with mosquitto"
    test_upgrade_from.c161dff.args.mqtt_domain="mqtt.domain.tld"
    test_upgrade_from.c161dff.args.domain="sub.domain.tld"
    test_upgrade_from.c161dff.args.path="/domoticz"

[Without_Mosquitto_upgrade_with_mosquitto]
    preinstall = """
    set -euxo pipefail
    yunohost domain add mqtt.domain.tld
    """

    preupgrade = """
    set -euxo pipefail
    yunohost app setting domoticz mqtt_domain -v mqtt.domain.tld
    """

    args.mqtt_domain="sub.domain.tld"
    only = ["upgrade","upgrade.c161dff"]

    test_upgrade_from.c161dff.name = "2024.6 without mosquitto"
    test_upgrade_from.c161dff.args.mqtt_domain="sub.domain.tld"
    test_upgrade_from.c161dff.args.domain="sub.domain.tld"
    test_upgrade_from.c161dff.args.path="/domoticz"
