#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

old_api=$(ynh_app_setting_get --key=api_path)
if [ "$new_path" == "/" ]; then
	new_api=/api_/$app
else
	new_api=/api_$new_path
fi

#=================================================
# CHECK WHICH PARTS SHOULD BE CHANGED
#=================================================

change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
	change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
	change_path=1
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

old_nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf
old_nginx_api_conf_path=/etc/nginx/conf.d/$old_domain.d/api_$app.conf

# Change the path in the NGINX config file
if [ $change_path -eq 1 ]
then
	# Make a backup of the original NGINX config file if modified
	ynh_backup_if_checksum_is_different "$old_nginx_conf_path"
	# Set global variables for NGINX helper
	domain="$old_domain"
	path_url="$new_path"
	path="$new_path"
	api_path="$new_api"
	# Create a dedicated NGINX config
	ynh_config_add_nginx
fi

# Change the domain for NGINX
if [ $change_domain -eq 1 ]
then
	# Delete file checksum for the old conf file location
	ynh_delete_file_checksum "$old_nginx_conf_path"
	ynh_delete_file_checksum "$old_nginx_api_conf_path"
	mv $old_nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
	ynh_replace --match="/etc/nginx/conf.d/$old_domain.d/" --replace="/etc/nginx/conf.d/$new_domain.d/" --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
	mv $old_nginx_api_conf_path /etc/nginx/conf.d/$new_domain.d/api_$app.conf
	# Store file checksum for the new config file location
	ynh_store_file_checksum "/etc/nginx/conf.d/$new_domain.d/$app.conf"
	ynh_store_file_checksum "/etc/nginx/conf.d/$new_domain.d/api_$app.conf"
fi

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression "Upgrading SSOwat configuration..."

# If the app is private, API should stays publicly accessible.
ynh_app_setting_delete --key="api_path"
ynh_app_setting_set --key="api_path" --value=$new_api
ynh_permission_url --permission api --url "$new_domain$new_api"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
